command:
  - "streamlit"
  - "run"
  - "frontend.py"
  - "--server.port=8000"
  - "--server.address=0.0.0.0"

resources:
  - name: requirements
    source:
      path: ./requirements.txt

env:
  - name: LAKEBASE_SECRET_SCOPE
    value: "database"
  - name: LAKEBASE_SECRET_KEY
    value: "lakebase-url"
  - name: TMDB_SECRET_SCOPE
    value: "database"
  - name: TMDB_SECRET_KEY
    value: "tmdb-api-key"

# Enable user authentication so X-Forwarded-User header is injected
authentication:
  user_claims:
    - email
